### ISSUE TITLE
Hacks for RSS readers?

### ISSUE THREAD

**Issue by untitaker** [dddddddddzzzz/api-oh#1]
I see on muan.co there's a way to like posts from RSS readers. Would a PR that adds this to the public API be accepted? If yes, maybe it should be standardized as well?

**Comment by muan** [comment]
The like implementation on my RSS feed is simply an auto submitting form. 

https://github.com/muan/site/commit/37b7c4c850a902b88bdff8b4f2c39acfa877ee73#diff-0c45df8bb007a6e86e6992a2b4dd39177dd47480983a392832a4ec97ead31989

There isn't anything the API needs to do differently.

**Comment by muan** [comment]
Hey~ thought you might be interested in https://github.com/dddddddddzzzz/api-oh/commit/266067587979bbfa4d55d557040dd9b6768e4640.

**Comment by untitaker** [comment]
ha yeah, i was thinking of writing something like that to make it all work better with HTMX. thanks.

about the RSS, the auto-submitting form will definitely work for my case too.
